services:
  postgres:
    image: postgres:15-alpine
    container_name: school-saas-db
    environment:
      - POSTGRES_USER:AlexCarvajal
      - POSTGRES_PASSWORD:9801
      - POSTGRES_DB:school_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: school-saas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: